import type{Profile,Recipe}from'./types';
const bonus={REST:0,CARDIO:100,STRENGTH:200,WOD:250} as const;
export const profiles:Profile[]=[
{id:'cedric',name:'Cédric',kind:'ADULT',baseCalories:2000,proteinTarget:165,activityBonus:bonus,heightCm:170,weightKg:90,targetWeightKg:80},
{id:'madame',name:'Corinne',kind:'ADULT',baseCalories:1450,proteinTarget:105,activityBonus:{REST:0,CARDIO:80,STRENGTH:120,WOD:160}},
{id:'family',name:'Famille',kind:'FAMILY',baseCalories:0,proteinTarget:0,activityBonus:{REST:0,CARDIO:0,STRENGTH:0,WOD:0},familyMembers:[{id:'girl14',name:'Fille 14 ans',age:14,activityLabel:'Active · CrossFit 2×/sem. + gym & natation',portionFactor:1},{id:'girl17',name:'Fille 17 ans',age:17,activityLabel:'Active · course 2×1 h/sem. + gym & natation',portionFactor:1}]}
];
export const recipes:Recipe[]=[
{id:'eggs',type:'BREAKFAST',title:'Œufs, jambon & tartine',subtitle:'Tomates à l’ail · pain complet',emoji:'🍳',minutes:10,minScale:.75,maxScale:1.45,tags:['salé','rapide'],steps:['Faire griller le pain.','Poêler les tomates avec l’ail et l’huile.','Cuire les œufs à ton goût et réchauffer le jambon.','Dresser le tout et assaisonner.'],ingredients:[{name:'Œufs',amount:2,unit:'piece',kcal:144,protein:13,scalable:false},{name:'Jambon',amount:60,unit:'g',kcal:70,protein:12},{name:'Pain complet',amount:60,unit:'g',kcal:150,protein:6},{name:'Tomates',amount:150,unit:'g',kcal:27,protein:1},{name:"Huile d'olive",amount:5,unit:'g',kcal:45,protein:0}]},
{id:'pancakes',type:'BREAKFAST',title:'Pancakes banane & skyr',subtitle:'Moelleux · fruits rouges · cannelle',emoji:'🥞',minutes:12,minScale:.7,maxScale:1.4,tags:['sucré','week-end'],steps:['Écraser la banane et mélanger avec l’œuf.','Ajouter flocons, skyr et cannelle.','Cuire de petits pancakes dans une poêle antiadhésive.','Servir avec les fruits rouges.'],ingredients:[{name:'Œuf',amount:1,unit:'piece',kcal:72,protein:6,scalable:false},{name:'Banane',amount:100,unit:'g',kcal:89,protein:1},{name:'Flocons d’avoine',amount:50,unit:'g',kcal:185,protein:6},{name:'Skyr',amount:120,unit:'g',kcal:76,protein:13},{name:'Fruits rouges',amount:80,unit:'g',kcal:38,protein:1}]},
{id:'bowl',type:'LUNCH',title:'Bowl poulet méditerranéen',subtitle:'Poulet rôti · quinoa · légumes',emoji:'🥗',minutes:12,minScale:.65,maxScale:1.4,tags:['meal prep','frais'],steps:['Réchauffer le quinoa et le poulet.','Couper ou réchauffer les légumes.','Assembler dans un grand bol.','Terminer avec la sauce yaourt et les herbes.'],ingredients:[{name:'Poulet',amount:150,unit:'g',kcal:248,protein:46},{name:'Quinoa cuit',amount:170,unit:'g',kcal:204,protein:7},{name:'Légumes',amount:250,unit:'g',kcal:90,protein:4},{name:'Sauce yaourt',amount:60,unit:'g',kcal:55,protein:4}]},
{id:'wrap',type:'LUNCH',title:'Wrap poulet César',subtitle:'Poulet · parmesan · crudités',emoji:'🌯',minutes:10,minScale:.7,maxScale:1.35,tags:['rapide','à emporter'],steps:['Réchauffer le wrap quelques secondes.','Ajouter poulet, salade et tomates.','Napper de sauce yaourt façon César.','Ajouter le parmesan, rouler et couper en deux.'],ingredients:[{name:'Wrap complet',amount:70,unit:'g',kcal:220,protein:7},{name:'Poulet',amount:140,unit:'g',kcal:231,protein:43},{name:'Crudités',amount:180,unit:'g',kcal:55,protein:3},{name:'Sauce César légère',amount:45,unit:'g',kcal:65,protein:3},{name:'Parmesan',amount:15,unit:'g',kcal:63,protein:6}]},
{id:'shake',type:'SNACK_PM',title:'Shake chocolat-banane',subtitle:'Whey · banane · lait · glaçons',emoji:'🥤',minutes:3,minScale:.65,maxScale:1.35,tags:['16 h','pré-WOD','express'],steps:['Mettre tous les ingrédients dans le blender.','Mixer 30 à 45 secondes avec des glaçons.','Ajuster avec un peu d’eau selon la texture voulue.'],ingredients:[{name:'Whey',amount:30,unit:'g',kcal:115,protein:23,scalable:false},{name:'Banane',amount:100,unit:'g',kcal:89,protein:1},{name:'Lait demi-écrémé',amount:150,unit:'ml',kcal:69,protein:5}]},
{id:'toast-snack',type:'SNACK_AM',title:'Toast jambon & fromage',subtitle:'Croustillant · simple · rassasiant',emoji:'🥪',minutes:5,minScale:.7,maxScale:1.35,tags:['10 h','salé','sans blender'],steps:['Faire griller le pain.','Ajouter jambon et fromage.','Passer une minute sous le grill si tu le veux chaud.'],ingredients:[{name:'Pain complet',amount:55,unit:'g',kcal:138,protein:6},{name:'Jambon',amount:55,unit:'g',kcal:64,protein:11},{name:'Fromage léger',amount:25,unit:'g',kcal:65,protein:7}]},
{id:'curry',type:'DINNER',title:'Poulet curry coco & riz',subtitle:'Crémeux · parfumé · souper commun',emoji:'🍛',minutes:25,minScale:.55,maxScale:1.4,tags:['famille','one pot'],steps:['Saisir le poulet avec le curry.','Ajouter les légumes et laisser colorer.','Verser le lait de coco et mijoter 8 à 10 minutes.','Servir avec le riz selon la portion NutriWeek.'],ingredients:[{name:'Poulet',amount:170,unit:'g',kcal:281,protein:52},{name:'Riz cuit',amount:220,unit:'g',kcal:286,protein:6},{name:'Légumes',amount:220,unit:'g',kcal:80,protein:4},{name:'Lait de coco léger',amount:100,unit:'ml',kcal:110,protein:1}]},
{id:'bolognese',type:'DINNER',title:'Spaghetti bolognaise maison',subtitle:'Bœuf · tomate · parmesan',emoji:'🍝',minutes:30,minScale:.55,maxScale:1.4,tags:['famille','comfort food'],steps:['Faire revenir le bœuf avec oignon et ail.','Ajouter la tomate et laisser mijoter.','Cuire les pâtes al dente.','Servir avec parmesan et basilic.'],ingredients:[{name:'Bœuf maigre',amount:150,unit:'g',kcal:260,protein:39},{name:'Spaghetti cuits',amount:220,unit:'g',kcal:330,protein:12},{name:'Sauce tomate',amount:180,unit:'g',kcal:90,protein:3},{name:'Parmesan',amount:15,unit:'g',kcal:63,protein:6}]}
,
{id:'overnight-oats',type:'BREAKFAST',title:'Overnight oats pomme-cannelle',subtitle:'Skyr · avoine · pomme · cannelle',emoji:'🥣',minutes:5,minScale:.7,maxScale:1.4,tags:['préparé la veille','sucré'],difficulty:'FACILE',batchFriendly:true,storageDays:2,ingredients:[{name:'Flocons d’avoine',amount:50,unit:'g',kcal:185,protein:6},{name:'Skyr',amount:150,unit:'g',kcal:95,protein:16},{name:'Pomme',amount:120,unit:'g',kcal:62,protein:0},{name:'Lait',amount:80,unit:'ml',kcal:37,protein:3}],steps:['Mélanger avoine, skyr et lait.','Ajouter la pomme en dés et la cannelle.','Réserver une nuit au frais.']},
{id:'salmon-toast',type:'BREAKFAST',title:'Toast saumon & œuf',subtitle:'Pain complet · saumon fumé · œuf',emoji:'🥚',minutes:10,minScale:.75,maxScale:1.35,tags:['salé','week-end'],difficulty:'FACILE',ingredients:[{name:'Pain complet',amount:70,unit:'g',kcal:175,protein:7},{name:'Saumon fumé',amount:60,unit:'g',kcal:105,protein:13},{name:'Œuf',amount:1,unit:'piece',kcal:72,protein:6,scalable:false},{name:'Fromage frais léger',amount:30,unit:'g',kcal:45,protein:3}],steps:['Griller le pain.','Cuire l’œuf.','Tartiner, ajouter saumon puis œuf.']},
{id:'turkey-wrap-breakfast',type:'BREAKFAST',title:'Wrap œuf & dinde',subtitle:'Œuf brouillé · dinde · fromage',emoji:'🌯',minutes:9,minScale:.75,maxScale:1.35,tags:['salé','rapide'],difficulty:'FACILE',ingredients:[{name:'Wrap complet',amount:60,unit:'g',kcal:189,protein:6},{name:'Œuf',amount:1,unit:'piece',kcal:72,protein:6,scalable:false},{name:'Dinde',amount:60,unit:'g',kcal:66,protein:13},{name:'Fromage léger',amount:25,unit:'g',kcal:65,protein:7}],steps:['Brouiller l’œuf.','Garnir le wrap avec dinde, œuf et fromage.','Rouler et toaster deux minutes.']},
{id:'yogurt-fruit-snack',type:'SNACK_AM',title:'Skyr, kiwi & amandes',subtitle:'Frais · croquant · sans préparation',emoji:'🥝',minutes:2,minScale:.7,maxScale:1.3,tags:['10 h','frais'],difficulty:'FACILE',ingredients:[{name:'Skyr',amount:150,unit:'g',kcal:95,protein:16},{name:'Kiwi',amount:100,unit:'g',kcal:61,protein:1},{name:'Amandes',amount:15,unit:'g',kcal:87,protein:3}],steps:['Couper le kiwi.','Servir avec le skyr et les amandes.']},
{id:'banana-peanut-snack',type:'SNACK_AM',title:'Banane & tartine cacahuète',subtitle:'Simple · rassasiant',emoji:'🍌',minutes:3,minScale:.7,maxScale:1.3,tags:['10 h','à emporter'],difficulty:'FACILE',ingredients:[{name:'Banane',amount:100,unit:'g',kcal:89,protein:1},{name:'Pain complet',amount:35,unit:'g',kcal:88,protein:3},{name:'Beurre de cacahuète',amount:12,unit:'g',kcal:71,protein:3}],steps:['Tartiner le pain.','Ajouter la banane à côté ou en rondelles.']},
{id:'pasta-pesto-chicken',type:'LUNCH',title:'Pasta poulet pesto',subtitle:'Tomates · roquette · parmesan',emoji:'🍝',minutes:15,minScale:.65,maxScale:1.4,tags:['meal prep','gourmand'],difficulty:'FACILE',batchFriendly:true,storageDays:3,ingredients:[{name:'Pâtes cuites',amount:190,unit:'g',kcal:285,protein:10},{name:'Poulet',amount:130,unit:'g',kcal:215,protein:40},{name:'Pesto',amount:20,unit:'g',kcal:92,protein:1},{name:'Tomates',amount:150,unit:'g',kcal:27,protein:1},{name:'Parmesan',amount:10,unit:'g',kcal:42,protein:4}],steps:['Cuire ou réchauffer pâtes et poulet.','Mélanger avec pesto et tomates.','Ajouter roquette et parmesan.']},
{id:'tuna-rice',type:'LUNCH',title:'Riz thon façon poke',subtitle:'Concombre · avocat · soja',emoji:'🍚',minutes:10,minScale:.65,maxScale:1.4,tags:['frais','à emporter'],difficulty:'FACILE',ingredients:[{name:'Riz cuit',amount:180,unit:'g',kcal:234,protein:5},{name:'Thon au naturel',amount:120,unit:'g',kcal:139,protein:31},{name:'Avocat',amount:60,unit:'g',kcal:96,protein:1},{name:'Concombre',amount:150,unit:'g',kcal:23,protein:1},{name:'Sauce soja',amount:15,unit:'ml',kcal:9,protein:1}],steps:['Déposer le riz dans le bol.','Ajouter thon, avocat et concombre.','Assaisonner avec soja et citron.']},
{id:'whey-yogurt-snack',type:'SNACK_PM',title:'Crème skyr chocolat',subtitle:'Skyr · whey cacao · fruits rouges',emoji:'🍫',minutes:3,minScale:.65,maxScale:1.35,tags:['16 h','protéiné'],difficulty:'FACILE',ingredients:[{name:'Skyr',amount:170,unit:'g',kcal:108,protein:18},{name:'Whey chocolat',amount:20,unit:'g',kcal:77,protein:15,scalable:false},{name:'Fruits rouges',amount:100,unit:'g',kcal:48,protein:1}],steps:['Mélanger skyr et whey.','Ajouter un trait d’eau si nécessaire.','Terminer avec les fruits rouges.']},
{id:'rice-cakes-snack',type:'SNACK_PM',title:'Galettes, dinde & banane',subtitle:'Digeste · pratique avant sport',emoji:'⚡',minutes:3,minScale:.7,maxScale:1.3,tags:['16 h','pré-WOD'],difficulty:'FACILE',ingredients:[{name:'Galettes de riz',amount:3,unit:'piece',kcal:90,protein:2},{name:'Dinde',amount:60,unit:'g',kcal:66,protein:13},{name:'Banane',amount:100,unit:'g',kcal:89,protein:1}],steps:['Garnir les galettes de dinde.','Manger la banane en accompagnement.']},
{id:'chili',type:'DINNER',title:'Chili con carne',subtitle:'Bœuf · haricots rouges · riz',emoji:'🌶️',minutes:30,minScale:.55,maxScale:1.4,tags:['famille','batch','congélation'],difficulty:'FACILE',batchFriendly:true,storageDays:3,freezerFriendly:true,ingredients:[{name:'Bœuf maigre',amount:140,unit:'g',kcal:243,protein:36},{name:'Haricots rouges',amount:120,unit:'g',kcal:132,protein:9},{name:'Riz cuit',amount:180,unit:'g',kcal:234,protein:5},{name:'Tomates',amount:180,unit:'g',kcal:54,protein:2},{name:'Maïs',amount:50,unit:'g',kcal:43,protein:2}],steps:['Faire revenir le bœuf et les épices.','Ajouter tomate, haricots et maïs.','Mijoter 15 minutes.','Servir avec le riz.']},
{id:'meatballs-pasta',type:'DINNER',title:'Boulettes tomate & pâtes',subtitle:'Bœuf · sauce tomate · basilic',emoji:'🍝',minutes:35,minScale:.55,maxScale:1.4,tags:['famille','batch'],difficulty:'MOYEN',batchFriendly:true,storageDays:3,freezerFriendly:true,ingredients:[{name:'Bœuf maigre',amount:150,unit:'g',kcal:260,protein:39},{name:'Pâtes cuites',amount:200,unit:'g',kcal:300,protein:11},{name:'Sauce tomate',amount:180,unit:'g',kcal:90,protein:3},{name:'Parmesan',amount:12,unit:'g',kcal:50,protein:5}],steps:['Former et colorer les boulettes.','Ajouter la sauce tomate et mijoter.','Cuire les pâtes.','Servir avec parmesan et basilic.']},
{id:'lasagna-skillet',type:'DINNER',title:'Lasagne express à la poêle',subtitle:'Bœuf · tomate · mozzarella',emoji:'🧀',minutes:30,minScale:.55,maxScale:1.4,tags:['famille','comfort food'],difficulty:'FACILE',batchFriendly:true,storageDays:3,ingredients:[{name:'Bœuf maigre',amount:130,unit:'g',kcal:225,protein:34},{name:'Pâtes à lasagne cuites',amount:180,unit:'g',kcal:270,protein:9},{name:'Sauce tomate',amount:200,unit:'g',kcal:100,protein:3},{name:'Mozzarella légère',amount:60,unit:'g',kcal:102,protein:13}],steps:['Faire revenir le bœuf.','Ajouter tomate et morceaux de lasagne précuits.','Laisser mijoter couvert.','Ajouter la mozzarella et gratiner.']},
{id:'teriyaki-chicken',type:'DINNER',title:'Poulet teriyaki & riz',subtitle:'Brocoli · sésame · sauce brillante',emoji:'🥢',minutes:25,minScale:.55,maxScale:1.4,tags:['famille','asiatique'],difficulty:'FACILE',ingredients:[{name:'Poulet',amount:160,unit:'g',kcal:264,protein:49},{name:'Riz cuit',amount:210,unit:'g',kcal:273,protein:6},{name:'Brocoli',amount:200,unit:'g',kcal:68,protein:6},{name:'Sauce teriyaki',amount:45,unit:'g',kcal:65,protein:2}],steps:['Saisir le poulet.','Ajouter la sauce et laisser caraméliser légèrement.','Cuire ou réchauffer le brocoli.','Servir avec riz et sésame.']},
{id:'burger-potatoes',type:'DINNER',title:'Burger maison & potatoes',subtitle:'Bœuf · cheddar · sauce maison',emoji:'🍔',minutes:30,minScale:.55,maxScale:1.35,tags:['famille','week-end'],difficulty:'FACILE',ingredients:[{name:'Pain burger',amount:75,unit:'g',kcal:205,protein:7},{name:'Steak haché maigre',amount:140,unit:'g',kcal:243,protein:36},{name:'Cheddar',amount:20,unit:'g',kcal:80,protein:5},{name:'Pommes de terre',amount:250,unit:'g',kcal:193,protein:5},{name:'Sauce maison',amount:25,unit:'g',kcal:55,protein:1}],steps:['Cuire les potatoes au four ou air fryer.','Cuire le steak et faire fondre le cheddar.','Monter le burger avec crudités et sauce.']},
{id:'salmon-orzo',type:'DINNER',title:'Saumon, orzo crémeux & épinards',subtitle:'Citron · parmesan · une seule casserole',emoji:'🐟',minutes:25,minScale:.55,maxScale:1.35,tags:['famille','one pot'],difficulty:'FACILE',ingredients:[{name:'Saumon',amount:150,unit:'g',kcal:312,protein:30},{name:'Orzo cuit',amount:190,unit:'g',kcal:285,protein:10},{name:'Épinards',amount:150,unit:'g',kcal:35,protein:4},{name:'Parmesan',amount:12,unit:'g',kcal:50,protein:5}],steps:['Cuire le saumon puis réserver.','Cuire l’orzo et incorporer les épinards.','Ajouter citron et parmesan.','Remettre le saumon au moment de servir.']}

];