import type{Profile,Recipe}from'./types';
const bonus={REST:0,CARDIO:100,STRENGTH:200,WOD:250} as const;
export const profiles:Profile[]=[
{id:'cedric',name:'Cédric',kind:'ADULT',baseCalories:2000,proteinTarget:165,activityBonus:bonus,heightCm:170,weightKg:90,targetWeightKg:80},
{id:'madame',name:'Corinne',kind:'ADULT',baseCalories:1450,proteinTarget:105,activityBonus:{REST:0,CARDIO:80,STRENGTH:120,WOD:160}},
{id:'family',name:'Famille',kind:'FAMILY',baseCalories:0,proteinTarget:0,activityBonus:{REST:0,CARDIO:0,STRENGTH:0,WOD:0}}
];
export const recipes:Recipe[]=[
{id:'eggs',type:'BREAKFAST',title:'Œufs, jambon & tartine',subtitle:'Tomates à l’ail · pain complet',emoji:'🍳',minutes:10,minScale:.75,maxScale:1.45,tags:['salé','rapide'],steps:['Faire griller le pain.','Poêler les tomates avec l’ail et l’huile.','Cuire les œufs à ton goût et réchauffer le jambon.','Dresser le tout et assaisonner.'],ingredients:[{name:'Œufs',amount:2,unit:'piece',kcal:144,protein:13,scalable:false},{name:'Jambon',amount:60,unit:'g',kcal:70,protein:12},{name:'Pain complet',amount:60,unit:'g',kcal:150,protein:6},{name:'Tomates',amount:150,unit:'g',kcal:27,protein:1},{name:"Huile d'olive",amount:5,unit:'g',kcal:45,protein:0}]},
{id:'pancakes',type:'BREAKFAST',title:'Pancakes banane & skyr',subtitle:'Moelleux · fruits rouges · cannelle',emoji:'🥞',minutes:12,minScale:.7,maxScale:1.4,tags:['sucré','week-end'],steps:['Écraser la banane et mélanger avec l’œuf.','Ajouter flocons, skyr et cannelle.','Cuire de petits pancakes dans une poêle antiadhésive.','Servir avec les fruits rouges.'],ingredients:[{name:'Œuf',amount:1,unit:'piece',kcal:72,protein:6,scalable:false},{name:'Banane',amount:100,unit:'g',kcal:89,protein:1},{name:'Flocons d’avoine',amount:50,unit:'g',kcal:185,protein:6},{name:'Skyr',amount:120,unit:'g',kcal:76,protein:13},{name:'Fruits rouges',amount:80,unit:'g',kcal:38,protein:1}]},
{id:'bowl',type:'LUNCH',title:'Bowl poulet méditerranéen',subtitle:'Poulet rôti · quinoa · légumes',emoji:'🥗',minutes:12,minScale:.65,maxScale:1.4,tags:['meal prep','frais'],steps:['Réchauffer le quinoa et le poulet.','Couper ou réchauffer les légumes.','Assembler dans un grand bol.','Terminer avec la sauce yaourt et les herbes.'],ingredients:[{name:'Poulet',amount:150,unit:'g',kcal:248,protein:46},{name:'Quinoa cuit',amount:170,unit:'g',kcal:204,protein:7},{name:'Légumes',amount:250,unit:'g',kcal:90,protein:4},{name:'Sauce yaourt',amount:60,unit:'g',kcal:55,protein:4}]},
{id:'wrap',type:'LUNCH',title:'Wrap poulet César',subtitle:'Poulet · parmesan · crudités',emoji:'🌯',minutes:10,minScale:.7,maxScale:1.35,tags:['rapide','à emporter'],steps:['Réchauffer le wrap quelques secondes.','Ajouter poulet, salade et tomates.','Napper de sauce yaourt façon César.','Ajouter le parmesan, rouler et couper en deux.'],ingredients:[{name:'Wrap complet',amount:70,unit:'g',kcal:220,protein:7},{name:'Poulet',amount:140,unit:'g',kcal:231,protein:43},{name:'Crudités',amount:180,unit:'g',kcal:55,protein:3},{name:'Sauce César légère',amount:45,unit:'g',kcal:65,protein:3},{name:'Parmesan',amount:15,unit:'g',kcal:63,protein:6}]},
{id:'shake',type:'SNACK_PM',title:'Shake chocolat-banane',subtitle:'Whey · banane · lait · glaçons',emoji:'🥤',minutes:3,minScale:.65,maxScale:1.35,tags:['16 h','pré-WOD','express'],steps:['Mettre tous les ingrédients dans le blender.','Mixer 30 à 45 secondes avec des glaçons.','Ajuster avec un peu d’eau selon la texture voulue.'],ingredients:[{name:'Whey',amount:30,unit:'g',kcal:115,protein:23,scalable:false},{name:'Banane',amount:100,unit:'g',kcal:89,protein:1},{name:'Lait demi-écrémé',amount:150,unit:'ml',kcal:69,protein:5}]},
{id:'toast-snack',type:'SNACK_AM',title:'Toast jambon & fromage',subtitle:'Croustillant · simple · rassasiant',emoji:'🥪',minutes:5,minScale:.7,maxScale:1.35,tags:['10 h','salé','sans blender'],steps:['Faire griller le pain.','Ajouter jambon et fromage.','Passer une minute sous le grill si tu le veux chaud.'],ingredients:[{name:'Pain complet',amount:55,unit:'g',kcal:138,protein:6},{name:'Jambon',amount:55,unit:'g',kcal:64,protein:11},{name:'Fromage léger',amount:25,unit:'g',kcal:65,protein:7}]},
{id:'curry',type:'DINNER',title:'Poulet curry coco & riz',subtitle:'Crémeux · parfumé · souper commun',emoji:'🍛',minutes:25,minScale:.55,maxScale:1.4,tags:['famille','one pot'],steps:['Saisir le poulet avec le curry.','Ajouter les légumes et laisser colorer.','Verser le lait de coco et mijoter 8 à 10 minutes.','Servir avec le riz selon la portion NutriWeek.'],ingredients:[{name:'Poulet',amount:170,unit:'g',kcal:281,protein:52},{name:'Riz cuit',amount:220,unit:'g',kcal:286,protein:6},{name:'Légumes',amount:220,unit:'g',kcal:80,protein:4},{name:'Lait de coco léger',amount:100,unit:'ml',kcal:110,protein:1}]},
{id:'bolognese',type:'DINNER',title:'Spaghetti bolognaise maison',subtitle:'Bœuf · tomate · parmesan',emoji:'🍝',minutes:30,minScale:.55,maxScale:1.4,tags:['famille','comfort food'],steps:['Faire revenir le bœuf avec oignon et ail.','Ajouter la tomate et laisser mijoter.','Cuire les pâtes al dente.','Servir avec parmesan et basilic.'],ingredients:[{name:'Bœuf maigre',amount:150,unit:'g',kcal:260,protein:39},{name:'Spaghetti cuits',amount:220,unit:'g',kcal:330,protein:12},{name:'Sauce tomate',amount:180,unit:'g',kcal:90,protein:3},{name:'Parmesan',amount:15,unit:'g',kcal:63,protein:6}]}
];